In [648]:
import pandas
import math
import sys
import numpy

In [688]:
def mymean(col):
    mysum = 0
    c = mycount(col)
    if not c:
        return numpy.nan
    for e in col:
        mysum += e
    return mysum/c

In [680]:
def mymin(col):
    if not mycount(col):
        return numpy.nan
    m = col.iloc[0];
    for e in list(col):
        if e < m:
            m = e
    return m

In [681]:
def mymax(col):
    if not mycount(col):
        return numpy.nan
    m = col.iloc[0]
    for e in list(col):
        if e > m:
            m = e
    return m

In [306]:
def mycount(col):
    count = 0;
    for e in col:
        count += 1;
    return count

In [675]:
def mystd(col):
    m = mymean(col);
    m2 = 0
    for e in list(col):
        m2 += (e - m) * (e - m)
    c = mycount(col)
    if not c:
        return numpy.nan
    m2 /= mycount(col)
    std = math.sqrt(m2)
    return std

In [687]:
pandas.set_option("max_columns", 100)

In [686]:
def describe(df, fields):
    index = ['count', 'mean', 'std', 'min', '25%', '50%', '75%', 'max']
    data = {}
    for field in fields:
        col = df[field].dropna()
        data[field] = [mycount(col), mymean(col), mystd(col), mymin(col), mypercentile(col, 25), mypercentile(col,50), mypercentile(col, 75), mymax(col)]
    describe_df = pandas.DataFrame(data)
    describe_df.index = index
    return describe_df

In [683]:
def mypercentile(col, percentile):
    if not mycount(col):
        return numpy.nan
    col_sorted = list(col.sort_values())
    i = (percentile * (mycount(col) - 1))/100
    if i.is_integer():
        p = col_sorted[int(i)]
    else:
        il = col_sorted[math.floor(i)]
        ih = col_sorted[math.ceil(i)]
        p = ih * (i - int(i)) + il * (1 - (i - int(i)))
    return p

In [685]:
if __name__ == "__main__":
    sys.argv[1] = "datasets/dataset_test.csv"
    if len(sys.argv) < 2:
        print("USAGE: describe.py <csv files>")
    else:
        df = pandas.read_csv(sys.argv[1])
        numeric_features = []
        for c in df.columns:
            col_type = df[c].dtype
            if col_type == float or col_type == int:
                numeric_features.append(c)
        describe_df = describe(df, numeric_features)
        print(describe_df)

['Index', 'Hogwarts House', 'Arithmancy', 'Astronomy', 'Herbology', 'Defense Against the Dark Arts', 'Divination', 'Muggle Studies', 'Ancient Runes', 'History of Magic', 'Transfiguration', 'Potions', 'Care of Magical Creatures', 'Charms', 'Flying']
            Index  Hogwarts House    Arithmancy   Astronomy   Herbology  \
count  400.000000             0.0    387.000000  387.000000  389.000000
mean   199.500000             0.0  50088.971576   48.155326    1.385517
std    115.469693             0.0  15452.744803  511.875159    5.048793
min      0.000000             NaN   4536.000000 -802.725180   -9.687662
25%     99.750000             NaN  40167.500000 -483.719690   -4.183731
50%    199.500000             NaN  49238.000000  292.108738    3.630490
75%    299.250000             NaN  60157.000000  508.713093    5.405685
max    399.000000             NaN  99744.000000  870.063498    9.678462

       Defense Against the Dark Arts  Divination  Muggle Studies  \
count                     392.000000  394.000000      390.000000
mean                       -0.537843    3.411071     -220.169594
std                         5.112229    3.886250      497.030335
min                        -8.700635   -8.183000    -1041.323658
25%                        -5.209348    3.528750     -580.049325
50%                        -2.915654    4.703000     -407.549022
75%                         4.785055    5.571000      221.387925
max                         8.027252    8.604000      939.317135

       Ancient Runes  History of Magic  Transfiguration     Potions  \
count     392.000000        389.000000       389.000000  390.000000
mean      495.937543          2.829816      1030.885777    5.776860
std       101.527670          4.311657        45.288575    3.213497
min       319.360250         -7.189090       906.932050   -1.162060
25%       400.719831          2.227669      1028.499974    3.230372
50%       484.102477          4.290164      1047.648405    5.731330
75%       591.372101          5.662488      1060.367924    8.136907
max       667.674165         10.366995      1099.966073   13.390013

       Care of Magical Creatures      Charms      Flying
count                 392.000000  400.000000  400.000000
mean                    0.022985 -243.181109   23.367450
std                     1.017705    8.716274   95.066887
min                    -2.871119 -259.866780 -143.520000
25%                    -0.646285 -250.150987  -38.475000
50%                     0.059416 -244.758710   -2.555000
75%                     0.711248 -232.798160   45.332500
max                     3.205525 -226.003820  282.430000

In [662]:
len(sys.argv)

3

In [670]:
df.describe()

,Index,Hogwarts House,Arithmancy,Astronomy,Herbology,Defense Against the Dark Arts,Divination,Muggle Studies,Ancient Runes,History of Magic,Transfiguration,Potions,Care of Magical Creatures,Charms,Flying
count,400.000000,0.0,387.000000,387.000000,389.000000,392.000000,394.000000,390.000000,392.000000,389.000000,389.000000,390.000000,392.000000,400.000000,400.000000
mean,199.500000,NaN,50088.971576,48.155326,1.385517,-0.537843,3.411071,-220.169594,495.937543,2.829816,1030.885777,5.776860,0.022985,-243.181109,23.367450
std,115.614301,NaN,15472.748364,512.537781,5.055295,5.118762,3.891192,497.668782,101.657418,4.317209,45.346899,3.217625,1.019005,8.727190,95.185944
min,0.000000,NaN,4536.000000,-802.725180,-9.687662,-8.700635,-8.183000,-1041.323658,319.360250,-7.189090,906.932050,-1.162060,-2.871119,-259.866780,-143.520000
25%,99.750000,NaN,40167.500000,-483.719690,-4.183731,-5.209348,3.528750,-580.049325,400.719831,2.227669,1028.499974,3.230372,-0.646285,-250.150987,-38.475000
50%,199.500000,NaN,49238.000000,292.108738,3.630490,-2.915654,4.703000,-407.549022,484.102477,4.290164,1047.648405,5.731330,0.059416,-244.758710,-2.555000
75%,299.250000,NaN,60157.000000,508.713093,5.405685,4.785055,5.571000,221.387925,591.372101,5.662488,1060.367924,8.136907,0.711248,-232.798160,45.332500
max,399.000000,NaN,99744.000000,870.063498,9.678462,8.027252,8.604000,939.317135,667.674165,10.366995,1099.966073,13.390013,3.205525,-226.003820,282.430000